/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/DaysCard copy.vue')['default']
    DaysCard: typeof import('./components/DaysCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HoursCard: typeof import('./components/HoursCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./components/Tabs.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
